### ISSUE TITLE
Trimming Markdown syntax marks

### ISSUE THREAD

**Issue by pcolladosoto** [wheleph/nttt#12]
## Description
When markdown syntax is used to format text (like add emphasis), the spaces also need to be trimmed. The most common ways are: single asterisk for italics (\**text here*\*), double asterisks for bold (\*\***text here**\*\*), and a back quote for code (\``text here`\`).

## Applicable to
All `.md` files.

## Acceptance criteria
+ In every `.md` file, spaces should be trimmed from the content of the following markdown formatting tags:
    + \*text here\*
    + \*\*text here\*\*
    + \*\*\*text here\*\*\*
    + \_text here\_
    + \_\_text here\_\_
    + \_\_\_text here\_\_\_
    + \`text here\`

## Ideas
+ Remove leading and trailing spaces inside markdown formatting blocks.
    + Access to the original (English) version of the file may make finding these entries easier.

## Issues
+ The original feature request only mentions a single back quote.
    + Are there situations that there is only a single back quote and not a pair of back quotes?
        + We haven't thought of any yet...
+ Are there any other markdown formatting blocks used? (For example, \*\*\****text here***\*\*\* for bold italics.)
    + Sometimes this is used for bold: \__text_\_ (double underscore).
    + And then we have this thing as well: \<kbd><kbd>text</kbd>\</kbd> which changes the font/style of the word.
    + And I have also seen \<code><code>text</code>\</code>. \<kbd> and \<code> are HTML formatting tags, whereas double underscores are markdown formating tags. See also issue 2 of feature #10.

**Comment by pcolladosoto** [comment]
This task was put back to In Progress because the code review is not yet finished.

#### Original author: Robert-Jan (@robertjank)

**Comment by ezeakis** [comment]
@wheleph @pcolladosoto @robertjank I see that this issue is in "code review". That means that someone has proceeded with it and I continue with another?

**Comment by wheleph** [comment]
No, it's just that a new column was introduced ("In review") and this issue was moved there. I guess it's better to move back to "In progress".

**Comment by ezeakis** [comment]
@wheleph @pcolladosoto @robertjank I have applied all corrections except this one

1. regular expression can identify capital letters, numbers and underscores but NOT spaces. 

Can we merge this functionality and discuss Nina's requirements for spaces on a different issue?

**Comment by wheleph** [comment]
@ezeakis show us the code :)

I don't see any open PR related to this issue.

**Comment by robertjank** [comment]
Yes, please create a PR and review for the current version.
