### ISSUE TITLE
Ensure proper formatting of the title tag

### ISSUE THREAD

**Issue by pcolladosoto** [wheleph/nttt#13]
## Description
The `collapse` block, which is itself related to the `title` tag, is formatted in a very specific way. Take a look at [this](https://docs.google.com/document/d/1d2IwEqW3fItiOwvfzyy8FEhLamZjSZBbHuquZxyKS60/edit) document for more context.

## Applicable to
All `.md` files.

## Acceptance criteria
+ Ensure that the formatting `title` tag follows this pattern in `.md` files:

    + ```markdown
      --- collapse ---
      ---
      title: Antwoord
      ---
      ``` 
## Open questions
+ What exact kinds of errors are we looking for?
+ Issues with colon in Chinese and Japanese?

## Notes
Take a look at issue 1 from #9.

## Ideas
+ Revert changes in these entries.
    + This requires access to the original (English) version of the file.

## Issues
+ What if the translator has translated the `title` tag?
    + Should it be corrected?
        + Yes, sadly because the tag is part of a larger string that needs to be translated, we can't hide `title`.
        + If this can be automated, it would be a good idea to include the colon that comes after as well due to the fact that it's different in Chinese and Japanese.

**Comment by pcolladosoto** [comment]
The issue is that volunteers sometimes translate the word `title` which then prevents the current version of `nttt` from ensuring this block is formatted correctly.

#### Original author: Raspberry Pi Translation

**Comment by wheleph** [comment]
Here's an example where we see the issue:
- Original: https://raw.githubusercontent.com/raspberrypilearning/stickers/master/en/step_1.md
- Translation: https://raw.githubusercontent.com/raspberrypilearning/stickers/l10n_master/uk-UA/step_1.md
- Crowdin UI: https://crowdin.com/translate/rpf-stickers/1958/en-uk?filter=basic&value=0
