### ISSUE TITLE
Correct language for volunteer acknowledgement

### ISSUE THREAD

**Issue by pcolladosoto** [wheleph/nttt#14]
## Description
Volunteer acknowledgement needs to be added in the correct language. Maja and Nina will keep a spreadsheet of all translated volunteer acknowledgements.

## Applicable to
The final `.md` file.

## Acceptance criteria
+ Volunteer acknowledgement section should be appended to the last `.md` file. The name of the file is `step_x.md` where `x` is the highest available number among the files.

+ The text of the acknowledgement is taken from [this](https://docs.google.com/spreadsheets/d/1gftThH2QukNPE3C34VINoKmt515eVjhca5cWOQryHNM/edit#gid=1717165158) spreadsheet.

+ Acknowledgement text should be separated by `***`. [Here](https://github.com/raspberrypilearning/mystery-letter/blob/master/nl-NL/step_9.md)'s an example. You can take a look at the raw file [here](https://raw.githubusercontent.com/raspberrypilearning/mystery-letter/master/nl-NL/step_9.md) so that you can take a better look at the `***` separator.

+ If for some reason acknowledgement text cannot be pulled from the spreadsheet (no internet access, no access rights, missing info...) a clear warning should be displayed and `nttt` should proceed to its next steps.

## Open questions
+ How can we determine the correct locale? Can we use the name of the folder where `.md` files are located or shall it be provided as a program argument? If the latter is to be chosen, take a look at issue #16.

## Ideas
+ Add translated volunteer acknowledgement manually.
    + This still requires a manual approach...
+ Extract translated volunteer acknowledgement from a file.

## Issues
+ Volunteer names still have to be added manually.
    + Sometimes the folders will contain steps that aren't used in the live project (usually the last step). So, for example, the folder will contain 10 steps, but the live version has 9 steps, which means that the volunteer acknowledgement needs to be automatically added to step 9, not 10. So I guess we'd have to spend some time tidying up Crowdin...
    + We could aim to tidy up Crowdin, but even if we miss a project or two, it's easier to copy the volunteer acknowledgement from step 10 to step 9 than having to open a spreadsheet and copy it out of there. So I guess either way, it will save us some time. But definitely need to tidy up projects in Crowdin when (if?) we have the time.
+ Translated volunteer acknowledgement should be added only once, when published for the first time.

**Comment by pcolladosoto** [comment]
The name of the folder where .md files are located is the locale code. The same locale codes are present in the spreadsheet containing the acknowledgement.

#### Original author: Raspberry Pi Translation

**Comment by wheleph** [comment]
@robertjank I tested this change and from functional standpoint it looks perfect to me.

Two suggestions:
- How about printing the URL of the file where NTTT pulls acknowledgements from in its output?
- Let's mention in README.md how to generate that CSV file from Google spreadsheet and the fact that it's updated with some delay: 
![Screenshot 2021-04-16 at 20 15 12](https://user-images.githubusercontent.com/2729981/115060690-d6527580-9ef0-11eb-923a-83126741ca39.png)

**Comment by wheleph** [comment]
When launching NTTT in Windows 10 command line I discovered some encoding-related issues:

```
C:\Users\wheleph>C:\Users\wheleph\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts\nttt -i "pro\nttt-test-results\Boat race\l10n_master\uk-UA" -e "pro\nttt-test-results\Boat race\master\en" -v Вова,Настя,Максим -o tmp\boat-race -L on
Input folder - 'C:\Users\wheleph\pro\nttt-test-results\Boat race\l10n_master\uk-UA'
Output folder - 'C:\Users\wheleph\tmp\boat-race'
English folder - 'C:\Users\wheleph\pro\nttt-test-results\Boat race\master\en'
Language - 'uk-UA'
Volunteers - '['????', '?????', '??????']'
Final step - '12'
Disabled functions - '[]'
Logging - 'on'
Find files ...
About to tidy up files:
 - \meta.yml
 - \step_1.md
 - \step_10.md
 - \step_11.md
 - \step_12.md
 - \step_2.md
 - \step_3.md
 - \step_4.md
 - \step_5.md
 - \step_6.md
 - \step_7.md
 - \step_8.md
 - \step_9.md
Continue (y/n):y
Fixing - \meta.yml
Fixing - \step_1.md
Fixing - \step_10.md
Fixing - \step_11.md
Fixing - \step_12.md
Fixing - \step_2.md
Fixing - \step_3.md
Fixing - \step_4.md
Fixing - \step_5.md
Fixing - \step_6.md
Fixing - \step_7.md
Fixing - \step_8.md
Fixing - \step_9.md
Adding volunteer acknowledgement - C:\Users\wheleph\tmp\boat-race\step_12.md
Using the volunteer acknowledgements from https://docs.google.com/spreadsheets/d/e/2PACX-1vS_oJDVBL9f0YQxISmtcCp8V1Hf4zjw1BwIhm-w5GMsvA8Y4VdT9JAUSueRXI5me5usLjblEPsNlqIH/pub?gid=1717165158&single=true&output=csv
Volunteer acknowledgement to be added:
Цей проєкт переклали волонтери:

????

?????

??????

Завдяки волонтерам, ми надаємо можливість людям у всьому світі навчатися рідною мовою. Ви також можете допомогти нам у цьому — більше інформації про волонтерську програму на [rpf.io/translate](https://rpf.io/translate).
Complete
Copying folders from C:\Users\wheleph\pro\nttt-test-results\Boat race\l10n_master\uk-UA to C:\Users\wheleph\tmp\boat-race:
 - images
 - resources
 - solutions
Copying files from C:\Users\wheleph\pro\nttt-test-results\Boat race\l10n_master\uk-UA to C:\Users\wheleph\tmp\boat-race:
 - scratch-translatable.txt

C:\Users\wheleph>
```

Names written in Cyrillic (Вова,Настя,Максим) are put in the target files as question marks.

@robertjank is it feasible to reproduce and fix this issue? Do you have access to a Windows computer?

If not please let me know. I have a Windows laptop around so I can play with it.

**Comment by robertjank** [comment]
Yes, I have access to Windows 8.1 and 10 machines and will investigate this problem. Thanks for finding this!

**Comment by robertjank** [comment]
Reproduced on Windows 8.1 (with Python 3.9.4 installed only for me) and on Windows 10 (with Python 3.9.4 installed for everyone).
- Running NTTT from the command line (Command Prompt or PowerShell) results in the names ending up as question marks in the MD file.
- Putting the NTTT command in a batch file doesn't work as well: if the file is saved as ASCII, then the names are turned into question marks at that time; if the file is saved as UTF-8, Windows doesn't recognise it as a batch file and won't execute it.
- Putting the NTTT command in a Windows shortcut is possible, but running the shortcut gives the same erroneous output.

Besides the NTTT executable nttt.exe, pip also creates a script nttt-script.py in the Scripts directory. When this script is used instead of the executable
```
python <path-to-Python39>\Scripts\nttt-script.py -i "Boat race\l10n_master\uk-UA" -e "Boat race\master\en" -o "Boat race\output\uk-UA" -v "Вова,Настя,Максим" -L on
```
the names end up correctly in the MD file:
```
Цей проєкт переклали волонтери:

Вова

Настя

Максим

Завдяки волонтерам, ми надаємо можливість людям у всьому світі навчатися рідною мовою. Ви також можете допомогти нам у цьому — більше інформації про волонтерську програму на [rpf.io/translate](https://rpf.io/translate).
```
Note that the logging (to stdout) still shows the names as question marks. This is a known deficiency of the Windows Command Prompt (and PowerShell as well). The solution for Windows 10 is still in Beta.

Obviously, having to use the script this way is pretty clumsy. Two more things to investigate:
1. Why does the executable generated by pip mess up the names where the script doesn't? Should pip be instructed to generate the executable with UTF-8 support?
2. What if we turn NTTT into a module, which can be invoked with `python -m nttt`? Is this easy and does it fix the problem?

**Comment by wheleph** [comment]
Thanks for your thorough investigation, @robertjank !

> This is a known deficiency of the Windows Command Prompt (and PowerShell as well)

Can you be more specific on that? What kind of deficiency are we dealing with exactly?

> 1. Why does the executable generated by pip mess up the names where the script doesn't? Should pip be instructed to generate the executable with UTF-8 support?

agree

> 2. What if we turn NTTT into a module, which can be invoked with python -m nttt? Is this easy and does it fix the problem?

That's a very good idea. In fact if NTTT was invoked that way then probably would not have the malarkey with `nttt` executable not being on Windows `PATH` (https://github.com/wheleph/nttt/issues/65).

Also we could look into using of Git Bash that's probably installed for every user of Git on Windows. That shell may handle Cyrillic better.

**Comment by robertjank** [comment]
> Can you be more specific on that? What kind of deficiency are we dealing with exactly?

I already noticed that logging to the console showed questions marks for non-ANSI characters, i.e. Windows can't display these characters and replaces them with question marks. The same seems to happen for command line arguments.
[This page](https://akr.am/blog/posts/using-utf-8-in-the-windows-terminal) provides a solution that works on Windows 10 (probably also requiring a not-too-old version). Actually only steps 4 and 5 are needed to get UTF-8 support in the Command Prompt.
I will add instructions to enable UTF-8 support to README.md.
