### ISSUE TITLE
Add missing subfolders

### ISSUE THREAD

**Issue by pcolladosoto** [wheleph/nttt#15]
# Description
Subfolders that are present in the English version, but missing in the translated version, should be added to the translated version, including content.

When the subfolders are empty (i.e. only contain the `.keep` file), Crowdin doesn't include them when it pushes the translations back to GitHub.

**Comment by robertjank** [comment]
Confirmed with @ninaszymor: The only thing to do is: if a subfolder (typically resources or solutions) is present in the English folder and not present in the translated folder, then copy the subfolder and its contents (typically a .keep file) from the English folder to the translated folder.

Not in scope of this issue:
- Missing individual files in the top-level folder or a subfolder. For example, a file is present in the images subfolder of the English folder, but in the translated version. Such a file should not be copied.
- Obsolete files or subfolders in the translated folder, i.e. files and subfolders that are present in the translated version, but are (no longer) present in the original version. These files and subfolders should not be deleted.
