### ISSUE TITLE
Extend command line arguments

### ISSUE THREAD

**Issue by robertjank** [wheleph/nttt#16]
The command line for `nttt` should be extended with additional arguments for the additional information that the tool needs.

The new command line should look like this:

`nttt [-h] [-i INPUT] [-o OUTPUT] [-e ENGLISH] [-l LANGUAGE] [-v VOLUNTEERS] [-f FINAL]`

Optional arguments:
```
-h, --help 
   Show this help message and exit.
-i INPUT, --input INPUT
    The input directory which contains the content to tidy up, defaults to the current folder.
-o OUTPUT, --output OUTPUT
    The output directory where the upgraded content should be written, defaults to the same as INPUT.
-e ENGLISH, --english ENGLISH
    The directory which contains the English files and folders, defaults to INPUT/../en.
-l LANGUAGE, --language LANGUAGE
    The language of the content to be tidied up, defaults to basename(INPUT).
-v VOLUNTEERS, --volunteers VOLUNTEERS
    The list of volunteers as a comma separated list, defaults to an empty list.
-f FINAL, --final FINAL
    The number of the final step file, defaults to the step file with the highest number.
```

**Comment by pcolladosoto** [comment]
Most likely this task will be implemented gradually in scope of other tasks that require those arguments. But it’s a good idea to gather those arguments here as a reference for the other tasks.

#### Original author: Volodymyr Sobotovych (@wheleph)
