### ISSUE TITLE
Improve nttt's end-of-line handling

### ISSUE THREAD

**Issue by pcolladosoto** [wheleph/nttt#17]
## Description
Currently (in version 0.1.0),`nttt` can only handle files that use `CR/LF` as end-of-line (eol) characters. This means that `nttt` may fail if lines end with only a `LF` character, like is usually the case on Linux and macOS systems.

`nttt` should be improved so that it can handle both files with lines ending with `CR/FL` as well as files with lines ending with `LF`.

**Comment by pcolladosoto** [comment]
Running `nttt` on identical files with different line endings yielded:
+ Identical `.md` files, except for the end-of-line characters.

+ The `meta.yml` with `LF` only was not processed correctly. Each step in the original version of this file consists of 2 lines, which `nttt` should concatenate into a single line.

The problem is in source file `tidyup.py` of `nttt` in two functions:

1. Function fix_meta corrects the steps in `meta.yml` and assumes that lines end with `\r\n` (CR/LF). A quick fix is to support both end-of-line styles, i.e. `\r\n` and `\n`. A better solution is to determine the end-of-line style of the file, e.g. by looking at the first line of the file, or using `os.linesep`.

2. Function fix_step corrects multiple things, some related to end-of-line characters:
    + Add newlines for `--- hints ---`, `--- hint ---` and `--- /hint ---` tags using `\r\n. This could be `\n, because Python corrects this automatically for the OS used (i.e. it becomes `\r\n` on Windows and `\n on Linux/macOS). An alternative is to use the end-of-line style of the file.

    + Searches for problems in `--- collapse ---` blocks, expecting `\r\n` as end-of-line characters, and fixes these problems. Instead of using `\r\n` to search, the end-of-line style of the file should be used, and should be used in the fixed output as well.

#### Original author: Robert-Jan (@robertjank)

**Comment by robertjank** [comment]
Tested the solution for this issue with the attached test data (about-me_nl-NL_CRLF.zip and about-me_nl-NL_LF.zip) on Windows and Linux. The output is correct: end-of-line characters are preserved, also when lines are combined or split.

**Comment by robertjank** [comment]
This is more a technical issue than a customer issue, so it is not necessary do customer testing.
