### ISSUE TITLE
Space inside HTML-code fragment should not be removed.

### ISSUE THREAD

**Issue by robertjank** [wheleph/nttt#37]
Project Guide to my country 1.0, language de-DE (and others), file step_13.md (and others).
NTTT replaces HTML-code fragments like `\`<td> </td>\`` with `\`<td></td>\``.
Although this space is after an HTML-tag (and before an HTML-tag as well), it should not be removed, because the HTML-code is inside back-quotes. In the original, English versioin, the space is also present between the HTML tags.

**Comment by wheleph** [comment]
@robertjank can you provide the repository URL where source for "Guide to my country 1.0" is present? I cannot find it at https://github.com/raspberrypilearning
