### ISSUE TITLE
Single quotes removed around step title containing a colon in meta.yml

### ISSUE THREAD

**Issue by robertjank** [wheleph/nttt#43]
Projects Boat race (languages ja-JP, zh-CN and zh-TW) and Rock, Paper, Scissors (language zh-CN).
The step titles containing a colon (typically challenges) are enclosed in single quotes in the input file, but the quotes are not present in the output file. This does not happen for other languages (the quotes are also in the output file), so this might be caused by the specific character set for Japanese and Chinese.

**Comment by wheleph** [comment]
To solve this we probably switch to ruamel: https://stackoverflow.com/questions/38369833/pyyaml-and-using-quotes-for-strings-only

**Comment by robertjank** [comment]
Looks like this could be a solution. (And a bit more future-proof since ruamel supports YAML 1.2.)
