### ISSUE TITLE
Spaces removed inside code block

### ISSUE THREAD

**Issue by robertjank** [wheleph/nttt#46]
Project Techno-shirt, languages ar-SA, de-DE, kn-IN and mr-IN, file step_8.md. This page contains fragments of C++ code inside triple back-quotes:
```
    uint32_t Wheel(byte WheelPos) {
        WheelPos = 255 - WheelPos;
        if(WheelPos < 85) {
            return strip.Color(255 - WheelPos * 3, 0, WheelPos * 3);
        }
        if(WheelPos < 170) {
            WheelPos -= 85;
            return strip.Color(0, WheelPos * 3, 255 - WheelPos * 3);
        }
        WheelPos -= 170;
        return strip.Color(WheelPos * 3, 255 - WheelPos * 3, 0);
    }
```
The asterisks inside this code block are not markdown tags, but C++ multiplication operators. NTTT removes some of the spaces, resulting in the following output:
```
    uint32_t Wheel(byte WheelPos) {
        WheelPos = 255 - WheelPos;
        if(WheelPos < 85) {
            return strip.Color(255 - WheelPos *3, 0, WheelPos* 3);
        }
        if(WheelPos < 170) {
            WheelPos -= 85;
            return strip.Color(0, WheelPos *3, 255 - WheelPos* 3);
        }
        WheelPos -= 170;
        return strip.Color(WheelPos *3, 255 - WheelPos* 3, 0);
    }
```
Although this does not break the C++ code, it makes it less readable.

**Comment by wheleph** [comment]
@robertjank can you provide a link to the repo for the project Techno-shirt. I couldn't find it neither in `nttt-test-results` nor in https://github.com/raspberrypilearning

**Comment by robertjank** [comment]
This is the repository for Techno-shirt: [https://github.com/raspberrypilearning/cd-intermediate-wearables-sushi.git](https://github.com/raspberrypilearning/cd-intermediate-wearables-sushi.git)
