### ISSUE TITLE
Correct words within tags

### ISSUE THREAD

**Issue by robertjank** [wheleph/nttt#54]
## Description
The translation engine used in CrowdIn sometimes capitalizes words in tags like `{:target="_blank"}` or `{:class="block3control"}`. Typically, keys `target` and `class` are being capitalized to `Target` and `Class`. This should be corrected by `nttt` to `target` and `class`.

## Open issues
- Does CrowdIn capitalize values like `_blank` and `block3control` (or parts of those values)?

**Comment by wheleph** [comment]
@majamanojlovic can you specify which parts of those tags should be convert to lowercase? Keys (like, `target`, `class` etc), values (like `block3control`, `_blank` etc) or both?

**Comment by majamanojlovic** [comment]
@wheleph everything needs to be lowercase.
