### ISSUE TITLE
Correct quotes within tags

### ISSUE THREAD

**Issue by robertjank** [wheleph/nttt#55]
## Description
The translation engine of CrowdIn, or the translators themselves, sometimes change the double quote characters in tags like `{:target="_blank"}` or `{:class="block3control"}` into quote characters specific to the translation language, like `“` and `”`. This should be corrected by `nttt` to the standard double quote character `"`.

**Comment by wheleph** [comment]
@robertjank do you have a specific list of quote characters that should be replaced?

**Comment by robertjank** [comment]
No, I don't, but maybe @majamanojlovic does?
Another option could be to bluntly replace the first character after the `=` with a `"` and the same for the last character before the `}`. Would that work @majamanojlovic? (Obviously, spaces should have been removed before this correction is applied.)

**Comment by wheleph** [comment]
Bluntly replacing characters sounds a bit dangerous to me.

I'd like to get some context. Where did this issue come from? Did you, Robert-Jan, experience it personally?

**Comment by robertjank** [comment]
No, it was brought up by Maja during the initial discussion about the feature covered by issue [#11](https://github.com/wheleph/nttt/issues/11); see also the section Issues in that issue.

**Comment by majamanojlovic** [comment]
@wheleph @robertjank I belive we only have issues with double quote characters `"` and full stops `.` This happens in Chinese and Japanese mostly.

**Comment by wheleph** [comment]
@majamanojlovic it would really help if you could provide an example from an existing project.

**Comment by majamanojlovic** [comment]
@wheleph Ok, I'll look into it today or tomorrow

**Comment by majamanojlovic** [comment]
@wheleph these are the only two examples I was able to find (I'll take another look next week and see if I can find more). None of these are on GitHub so you'll have to check them out in Crowdin but I'm not sure if you'll be able to access them?

This string has been corrected but you can see the last suggestion has the mentioned issue with a colon `:` (I just realised that i said full stop in the previous comment): 
https://crowdin.com/translate/about-me/2906/en-ja#25551

And in this one the double quotes are wrong:
https://crowdin.com/translate/rpf-ghostbusters/1425/en-ja#243784

Does this help?

**Comment by wheleph** [comment]
@majamanojlovic thanks, this is exactly what I need.

I don't have access to the projects in Crowndin though but I requested access to them via Crowdin UI so hopefully the request hit your inbox sometime soon.

**Comment by majamanojlovic** [comment]
@wheleph just approved it - let me know if it doesn't work.

**Comment by wheleph** [comment]
Perfect! I'm putting the troublesome translations below for easier reference. 

Incorrect colon symbol:
```
このプロジェクトは、Webブラウザで <0>trinket.io</0>{：target = "_ blank"}を使用して完成させることができます。
```

Incorrect quotes:
```
<0>おばけのスプライトが押されたとき</0>{:class=”blockevents”}、<0>スコア</0>{:class=”block3variables”}を<0>1ずつ変える</0>{:class=”block3variables”}必要があります。
```

In scope of this ticket I propose to fix only the two cases outlined above.

If you find any other cases in future please raise a new issue.

**Comment by wheleph** [comment]
Also, handle two quote marks ('') instead of a double qoutes
