### ISSUE TITLE
Validate the meta.yml translation

### ISSUE THREAD

**Issue by pcolladosoto** [wheleph/nttt#7]
## Synopsis
Ensure that nothing except title, description and steps is translated in meta.yml

## Description
We should ensure that only the following are translated:
- `title`
- `description`
- `steps`

## Applicable to
`meta.yml`

## Acceptance criteria
+ If any other keys are translated they should be replaced with English originals from `en/meta.yml`.

## Ideas
+ Prevent translators (including reviewers and testers) from changing the translation for all entries, except for tags `title`, `description` and `steps`.
    + Can this be achieved in Crowdin?
         + One option would be to use their [REST API](https://support.crowdin.com/api/v2/) to look for predefined strings and make them hidden automatically instead of manually. This can be implemented in another Python script. That will not prevent proofreaders from unhiding though.
    + It won't work for already translated projects.
+ Revert changes in entries (except for the allowed ones).
    + This requires access to the original (English) version of the file.

## Issues
+ What if the translator has translated some of the `title`, `description` and `steps` tags?
    + Not possible in recent projects.

**Comment by robertjank** [comment]
Probably depends on #16.

**Comment by pcolladosoto** [comment]
In order for the script to understand that a key is translated or not, beside the translated files, it should have the original files in English as input as well.

#### Original author -> Manos Zeakis

**Comment by pcolladosoto** [comment]
The above is true. Please see the **Tool Design** section from the wiki that contains a discussion on the proposed tool's inputs and outputs.

#### Original author: Robert-Jan (@robertjank)

**Comment by pcolladosoto** [comment]
As @robertjank stated above:
> Probably depends on #16.

This implies that these modifications on input should at one point be issues/features to implement in the code. Until then, enhancements like this one cannot implemented.

#### Original author: Manos Zeakis (@ezeakis)
